# -*- coding: utf-8 -*-
"""YOLOv7_train_LP_Detection.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1kjKGz2OyRDhZKgkJGA87eIntSCJ50lrb
"""

from google.colab import drive
drive.mount('/content/drive')

"""### Requirements"""

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/drive/MyDrive
!mkdir YOLOv7_train

# Commented out IPython magic to ensure Python compatibility.
# clone souce code YOLOv7 ve YOLOv7_train
# %cd /content/drive/MyDrive/YOLOv7_train
!git clone https://github.com/WongKinYiu/yolov7.git

# Commented out IPython magic to ensure Python compatibility.
# cai dat cac thu vien can thiet train yolov7
# %cd /content/drive/MyDrive/YOLOv7_train/yolov7
!pip install -r requirements.txt

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/drive/MyDrive/YOLOv7_train/yolov7
!pip install roboflow

# Commented out IPython magic to ensure Python compatibility.
# tai weight pretrain de nhan dien thu
# %cd /content/drive/MyDrive/YOLOv7_train/yolov7
!mkdir pretrain
# %cd pretrain
!wget https://github.com/WongKinYiu/yolov7/releases/download/v0.1/yolov7.pt

# Commented out IPython magic to ensure Python compatibility.
# test anh tu Internet
# %cd /content/drive/MyDrive/YOLOv7_train/yolov7
!mkdir test_images
# %cd test_images
!wget https://cdnimg.vietnamplus.vn/uploaded/izhsa/2019_09_19/ttxvn_canh_sat_giao_thong_binh_duong_khang_dinh_cap_mot_bks_61a_66666_duy_nhat_162920275_4085687.jpg
!wget https://danviet.mediacdn.vn/upload/2-2017/images/2017-05-19/149518917917025-xe-bus.jpg
!wget https://vnanet.vn/Data/Articles/2018/09/01/388809/vna_potal_tien_giang_luong_phuong_tien_giao_thong_tang_nhung_khong_xay_ra_un_tac_nghiem_trong_124946874_stand.jpg

# Commented out IPython magic to ensure Python compatibility.
# Nhan dien thu với weight pretrain
# %cd /content/drive/MyDrive/YOLOv7_train/yolov7
!python detect.py --weights pretrain/yolov7.pt --source test_images/ttxvn_canh_sat_giao_thong_binh_duong_khang_dinh_cap_mot_bks_61a_66666_duy_nhat_162920275_4085687.jpg

# Xem ảnh nhận diện từ thư mục
from IPython.display import Image, display
display(Image(filename='/content/drive/MyDrive/YOLOv7_train/yolov7/runs/detect/exp/ttxvn_canh_sat_giao_thong_binh_duong_khang_dinh_cap_mot_bks_61a_66666_duy_nhat_162920275_4085687.jpg'))

"""
### Data Analysis_1

"""

# Commented out IPython magic to ensure Python compatibility.
# Giải nén dữ liệu để train model
# %cd /content/drive/MyDrive/YOLOv7_train
# !mkdir train_data
!unzip /content/drive/MyDrive/YOLOv7_train/train_data/datazip/yolo_plate_dataset.zip

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/drive/MyDrive/YOLOv7_train/train_data
# !mkdir dataset
!mv /content/drive/MyDrive/YOLOv7_train/train_data/datazip/yolo_plate_dataset /content/drive/MyDrive/YOLOv7_train/train_data/dataset

import os
len(os.listdir('/content/drive/MyDrive/YOLOv7_train/train_data/dataset/yolo_plate_dataset'))

!rm /content/drive/MyDrive/YOLOv7_train/train_data/dataset/yolo_plate_dataset/classes.txt

!rm /content/drive/MyDrive/YOLOv7_train/train_data/dataset/yolo_plate_dataset/desktop.ini

# Commented out IPython magic to ensure Python compatibility.
# Tổ chức lại thư mục train vì YOLOv7 yêu cầu thư mục train có hai thư mục con là image và label:
# train: 
# - images
# - labels
# test: 
# - images
# - labels

# %cd /content/drive/MyDrive/YOLOv7_train
!pip install split-folders[full]

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/drive/MyDrive/YOLOv7_train/train_data
import splitfolders
input_folder = '/content/drive/MyDrive/YOLOv7_train/train_data/dataset'
splitfolders.ratio(input_folder, output="output", seed=1337, ratio=(.8, .1, .1), group_prefix=2, move=True)

!mkdir /content/drive/MyDrive/YOLOv7_train/train_data/output/test/images
!mkdir /content/drive/MyDrive/YOLOv7_train/train_data/output/test/labels
!mv /content/drive/MyDrive/YOLOv7_train/train_data/output/test/yolo_plate_dataset/*.jpg /content/drive/MyDrive/YOLOv7_train/train_data/output/test/images
!mv /content/drive/MyDrive/YOLOv7_train/train_data/output/test/yolo_plate_dataset/*.txt /content/drive/MyDrive/YOLOv7_train/train_data/output/test/labels

!rm -rf /content/drive/MyDrive/YOLOv7_train/train_data/output/test/yolo_plate_dataset

!mkdir /content/drive/MyDrive/YOLOv7_train/train_data/output/train/images
!mkdir /content/drive/MyDrive/YOLOv7_train/train_data/output/train/labels
!mv /content/drive/MyDrive/YOLOv7_train/train_data/output/train/yolo_plate_dataset/*.jpg /content/drive/MyDrive/YOLOv7_train/train_data/output/train/images
!mv /content/drive/MyDrive/YOLOv7_train/train_data/output/train/yolo_plate_dataset/*.txt /content/drive/MyDrive/YOLOv7_train/train_data/output/train/labels

!rm -rf /content/drive/MyDrive/YOLOv7_train/train_data/output/train/yolo_plate_dataset

!mkdir /content/drive/MyDrive/YOLOv7_train/train_data/output/val/images
!mkdir /content/drive/MyDrive/YOLOv7_train/train_data/output/val/labels
!mv /content/drive/MyDrive/YOLOv7_train/train_data/output/val/yolo_plate_dataset/*.jpg /content/drive/MyDrive/YOLOv7_train/train_data/output/val/images
!mv /content/drive/MyDrive/YOLOv7_train/train_data/output/val/yolo_plate_dataset/*.txt /content/drive/MyDrive/YOLOv7_train/train_data/output/val/labels

!rm -rf /content/drive/MyDrive/YOLOv7_train/train_data/output/val/yolo_plate_dataset

"""### Train Model"""

# Commented out IPython magic to ensure Python compatibility.
# Khai báo 1 file yaml để YOLOv7 biết:
# Đường dẫn đến thư mục train, test (nếu có, nếu không thì dùng luôn đến train) 
# Số lượng class qua biến nc (number of class)
# Tên của các class

# %cd /content/drive/MyDrive/YOLOv7_train/yolov7
!rm data/mydataset.yaml #nếu có
!echo 'train: /content/drive/MyDrive/YOLOv7_train/train_data/output/train' >> data/mydataset.yaml
!echo 'val: /content/drive/MyDrive/YOLOv7_train/train_data/output/val' >> data/mydataset.yaml
!echo 'test: /content/drive/MyDrive/YOLOv7_train/train_data/output/test' >> data/mydataset.yaml
!echo 'nc: 1' >> data/mydataset.yaml
!echo "names: ['plate']" >> data/mydataset.yaml

# Commented out IPython magic to ensure Python compatibility.
# Train model YOLOv7 với dữ liệu license plates
# %cd /content/drive/MyDrive/YOLOv7_train/yolov7
!python train.py --batch 16 --cfg cfg/training/yolov7.yaml --epochs 100 --data data/mydataset.yaml --weights 'runs/train/exp/weights/last.pt'

# Commented out IPython magic to ensure Python compatibility.
# Nhận diện biển số xe với weights vừa train
# %cd /content/drive/MyDrive/YOLOv7_train/yolov7
!python detect.py --weights /content/drive/MyDrive/YOLOv7_train/yolov7/runs/train/exp2/weights/best.pt --source /content/drive/MyDrive/YOLOv7_train/yolov7/test_images/xemay.jpg

# Commented out IPython magic to ensure Python compatibility.
# Xem ảnh nhận diện từ thư mục
# %cd /content/drive/MyDrive/YOLOv7_train/yolov7
from IPython.display import Image, display
display(Image(filename='runs/detect/exp3/xemay.jpg'))

# Commented out IPython magic to ensure Python compatibility.
# Lưu file train last
# %cd /content/drive/MyDrive/YOLOv7_train
# !mkdir save_model_fol
!cp /content/drive/MyDrive/YOLOv7_train/yolov7/runs/train/exp2/weights/last.pt /content/drive/MyDrive/YOLOv7_train/save_model_fol